version: "3.8"

services:
  dev-env:
    build: .
    image: projet-ml-env:latest
    container_name: python_ml_dev
    volumes:
      - .:/app
    stdin_open: true # Equivalent de -i
    tty: true # Equivalent de -t
